import {Point,Rect,Scene,Report,Result,Diagnostic} from './types.js';
import {validateInput} from './schema.js';
const EPS=.01, CLEAR=3, STROKE=1.25;
const fail=(d:Diagnostic):Result<Scene>=>({ok:false,error:d,report:{ok:false,diagnostics:[d],crossings:0}});
const finite=(p:Point)=>Number.isFinite(p.x)&&Number.isFinite(p.y);
const inside=(p:Point,r:Rect)=>p.x>r.x+EPS&&p.x<r.x+r.width-EPS&&p.y>r.y+EPS&&p.y<r.y+r.height-EPS;
const boundary=(p:Point,r:Rect)=>
 ((Math.abs(p.x-r.x)<EPS||Math.abs(p.x-r.x-r.width)<EPS)&&p.y>=r.y-EPS&&p.y<=r.y+r.height+EPS)||
 ((Math.abs(p.y-r.y)<EPS||Math.abs(p.y-r.y-r.height)<EPS)&&p.x>=r.x-EPS&&p.x<=r.x+r.width+EPS);
const normal=(side:string):Point=>side==='EAST'?{x:1,y:0}:side==='WEST'?{x:-1,y:0}:side==='NORTH'?{x:0,y:-1}:{x:0,y:1};
function segHitsRect(a:Point,b:Point,r:Rect){ // strict interior, orthogonal segments
 if(a.x===b.x)return a.x>r.x+EPS&&a.x<r.x+r.width-EPS&&Math.max(Math.min(a.y,b.y),r.y+EPS)<Math.min(Math.max(a.y,b.y),r.y+r.height-EPS);
 if(a.y===b.y)return a.y>r.y+EPS&&a.y<r.y+r.height-EPS&&Math.max(Math.min(a.x,b.x),r.x+EPS)<Math.min(Math.max(a.x,b.x),r.x+r.width-EPS);
 return false;
}
function overlap(a:Rect,b:Rect){return Math.max(a.x,b.x)<Math.min(a.x+a.width,b.x+b.width)-EPS&&Math.max(a.y,b.y)<Math.min(a.y+a.height,b.y+b.height)-EPS}
function rectSegmentDistance(r:Rect,a:Point,b:Point){const dx=Math.max(r.x-Math.max(a.x,b.x),Math.min(a.x,b.x)-(r.x+r.width),0),dy=Math.max(r.y-Math.max(a.y,b.y),Math.min(a.y,b.y)-(r.y+r.height),0);return Math.hypot(dx,dy)}
export function validateScene(scene:Scene,originalInput?:unknown):Result<Scene>{
 if(!scene||scene.version!==1||!Array.isArray(scene.nodes)||!Array.isArray(scene.edges))return fail({code:'INVALID_GEOMETRY',rule:'scene',message:'invalid resolved scene'});
 const semantic=validateInput(scene.source);if(!semantic.ok)return fail({code:'INVALID_GEOMETRY',rule:'source',message:`resolved scene has invalid source: ${semantic.error.message}`});
 if(originalInput!==undefined){const original=validateInput(originalInput);if(!original.ok||JSON.stringify(original.value)!==JSON.stringify(scene.source))return fail({code:'INVALID_GEOMETRY',rule:'source-correspondence',message:'resolved scene source does not match the supplied semantic input'});}
 if(scene.print){const t=scene.print.transform;if(!t||![t.width,t.height,t.translateX,t.translateY,t.scale].every(Number.isFinite)||t.width!==scene.print.target.width||t.height!==scene.print.target.height||Math.abs(t.translateX-scene.print.target.margin)>EPS||Math.abs(t.translateY-scene.print.target.margin)>EPS||Math.abs(t.scale-scene.print.fitScale)>EPS||t.scale<=0)return fail({code:'INVALID_GEOMETRY',rule:'print-transform',message:'resolved page transform is invalid'});}
 const ids=new Set(scene.nodes.map(n=>n.id)); if(ids.size!==scene.nodes.length)return fail({code:'INVALID_GEOMETRY',rule:'node-count',message:'duplicate resolved node'});
 const declaredContinuations=scene.source?.continuations??[],resolvedContinuations=scene.continuations??[];
 if(declaredContinuations.length!==resolvedContinuations.length||declaredContinuations.some(c=>resolvedContinuations.filter(r=>r.incomingEdge===c.incomingEdge&&r.outgoingEdge===c.outgoingEdge&&r.throughNode===c.throughNode).length!==1))return fail({code:'INVALID_GEOMETRY',rule:'continuation-preservation',message:'resolved continuations differ from declared source'});
 if(!Array.isArray(scene.ports)||scene.ports.length!==scene.edges.length*2)return fail({code:'INVALID_GEOMETRY',rule:'ports',message:'scene lacks independent ports'});
 // The semantic source is checked against rendered geometry; do not trust it merely as metadata.
 if(scene.source.nodes.length!==scene.nodes.length||scene.source.edges.length!==scene.edges.length)return fail({code:'INVALID_GEOMETRY',rule:'preservation',message:'scene drops or adds declared content'});
 for(const n of scene.source.nodes){const actual=scene.nodes.find(x=>x.id===n.id);if(!actual||actual.title!==n.title||actual.body!==n.body||actual.state!==n.state||actual.kind!==n.kind||actual.presentation!==n.presentation||actual.canonicalNodeId!==(n.canonicalNodeId??n.id)||actual.showcasePage!==n.showcasePage||JSON.stringify(actual.rows)!==JSON.stringify(n.rows)||n.rows?.some((row,i)=>JSON.stringify(row)!==JSON.stringify(Object.fromEntries(Object.entries(actual.resolvedRows?.[i]??{}).filter(([key])=>!['renderedText','lines','bounds'].includes(key))))))return fail({code:'INVALID_GEOMETRY',rule:'preservation',ids:[n.id],message:'node text, identity, or structured content changed'});}
 for(const e of scene.source.edges){const actual=scene.edges.find(x=>x.id===e.id);if(!actual||actual.source!==e.source||actual.target!==e.target||actual.label!==e.label||actual.displayLabel!==e.displayLabel||JSON.stringify(actual.labelParts)!==JSON.stringify(e.labelParts)||actual.labelPlacement!==e.labelPlacement||actual.semanticClass!==e.semanticClass||actual.style!==e.style)return fail({code:'INVALID_GEOMETRY',rule:'preservation',ids:[e.id],message:'edge semantics changed'});}
 for(const n of scene.nodes){const r=n.box;if(![r.x,r.y,r.width,r.height].every(Number.isFinite)||r.width<=0||r.height<=0)return fail({code:'INVALID_GEOMETRY',rule:'node-bounds',ids:[n.id],message:'invalid node box'});if(r.x<CLEAR||r.y<CLEAR||r.x+r.width>scene.canvas.width-CLEAR||r.y+r.height>scene.canvas.height-CLEAR)return fail({code:'INVALID_GEOMETRY',rule:'canvas',ids:[n.id],message:'node clips canvas'});}
 for(let i=0;i<scene.nodes.length;i++)for(let j=i+1;j<scene.nodes.length;j++)if(overlap(scene.nodes[i].box,scene.nodes[j].box))return fail({code:'INVALID_GEOMETRY',rule:'node-overlap',ids:[scene.nodes[i].id,scene.nodes[j].id],message:'node boxes overlap'});
 if(scene.source.theme?.visual)for(const n of scene.nodes){
  const boxes=[n.titleBounds,...(n.stateBox?[n.stateBox]:[]),...(n.resolvedRows??[]).map(r=>r.bounds)].filter((r):r is Rect=>!!r);
  for(const r of boxes)if(r.x<n.box.x||r.y<n.box.y||r.x+r.width>n.box.x+n.box.width+EPS||r.y+r.height>n.box.y+n.box.height+EPS)return fail({code:'INVALID_GEOMETRY',rule:'text-containment',ids:[n.id],message:'measured node content exceeds its box'});
  for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++)if(overlap(boxes[i],boxes[j]))return fail({code:'INVALID_GEOMETRY',rule:'text-overlap',ids:[n.id],message:'measured node content overlaps'});
 }
 const used=new Map<string,Point[]>(); let crossings=0;
 for(const e of scene.edges){if(!ids.has(e.source)||!ids.has(e.target)||e.points.length<2)return fail({code:'INVALID_GEOMETRY',rule:'edge',ids:[e.id],message:'edge is incomplete'});const s=scene.nodes.find(n=>n.id===e.source)!,t=scene.nodes.find(n=>n.id===e.target)!;let [a,b]=[e.points[0],e.points.at(-1)!];if(!e.continuedAtTarget&&(!e.arrowhead||e.arrowhead.length!==3||Math.abs(e.arrowhead[0].x-b.x)>EPS||Math.abs(e.arrowhead[0].y-b.y)>EPS||inside(e.arrowhead[1],t.box)||inside(e.arrowhead[2],t.box)))return fail({code:'INVALID_GEOMETRY',rule:'arrowhead',ids:[e.id],message:'target arrowhead does not reach boundary cleanly'});const sp=scene.ports.find(p=>p.id===`${e.id}:source`),tp=scene.ports.find(p=>p.id===`${e.id}:target`);if(!sp||!tp||sp.nodeId!==e.source||tp.nodeId!==e.target||Math.abs(sp.point.x-a.x)>EPS||Math.abs(sp.point.y-a.y)>EPS||Math.abs(tp.point.x-b.x)>EPS||Math.abs(tp.point.y-b.y)>EPS)return fail({code:'INVALID_GEOMETRY',rule:'ports',ids:[e.id],message:'edge endpoints do not match declared ports'});if(!finite(a)||!finite(b)||!boundary(a,s.box)||!boundary(b,t.box))return fail({code:'INVALID_GEOMETRY',rule:'attachment',ids:[e.id],message:'edge endpoint is not on its declared box'});const sn=normal(sp.side),tn=normal(tp.side),next=e.points[1],prev=e.points[e.points.length-2];if((next.x-a.x)*sn.x+(next.y-a.y)*sn.y<=EPS||(b.x-prev.x)*tn.x+(b.y-prev.y)*tn.y>=-EPS)return fail({code:'INVALID_GEOMETRY',rule:'direction',ids:[e.id],message:'edge does not leave and enter through declared port directions'});for(const p of [a,b]){let v=used.get(`${p.x},${p.y}`)??[];if(v.length)return fail({code:'INVALID_GEOMETRY',rule:'distinct-ports',ids:[e.id],message:'independent edges share an attachment'});v.push(p);used.set(`${p.x},${p.y}`,v)}
 for(let i=0;i<e.points.length-1;i++){a=e.points[i];b=e.points[i+1];if(!(a.x===b.x||a.y===b.y)||(!i&&a.x===b.x&&b.y===a.y)||!finite(a)||!finite(b))return fail({code:'INVALID_GEOMETRY',rule:'orthogonal',ids:[e.id],message:'edge segment is invalid'});for(const n of scene.nodes)if(segHitsRect(a,b,n.box))return fail({code:'INVALID_GEOMETRY',rule:'box-clearance',ids:[e.id,n.id],message:'external edge enters a node interior'});}
 // A route may bend or cross itself, but may never retrace any of its own segments.
 for(let i=0;i<e.points.length-1;i++)for(let j=i+1;j<e.points.length-1;j++){
  const a=e.points[i],b=e.points[i+1],c=e.points[j],d=e.points[j+1];
  const vertical=a.x===b.x&&c.x===d.x&&Math.abs(a.x-c.x)<EPS;
  const horizontal=a.y===b.y&&c.y===d.y&&Math.abs(a.y-c.y)<EPS;
  if(vertical||horizontal){const lo=Math.max(vertical?Math.min(a.y,b.y):Math.min(a.x,b.x),vertical?Math.min(c.y,d.y):Math.min(c.x,d.x)),hi=Math.min(vertical?Math.max(a.y,b.y):Math.max(a.x,b.x),vertical?Math.max(c.y,d.y):Math.max(c.x,d.x));if(hi>lo+EPS)return fail({code:'INVALID_GEOMETRY',rule:'self-retrace',ids:[e.id],message:'edge retraces its own segment'});}
 }
 if(e.label!==undefined&&!e.labelBox)return fail({code:'INVALID_GEOMETRY',rule:'label-preservation',ids:[e.id],message:'labeled edge lacks label geometry'});
 if(!e.continuedAtTarget&&(!e.arrowhead||e.arrowhead.length!==3||Math.abs(e.arrowhead[0].x-b.x)>EPS||Math.abs(e.arrowhead[0].y-b.y)>EPS||inside(e.arrowhead[1],t.box)||inside(e.arrowhead[2],t.box)))return fail({code:'INVALID_GEOMETRY',rule:'arrowhead',ids:[e.id],message:'target arrowhead does not reach boundary cleanly'});
 if(e.labelBox){if(Math.min(...e.points.slice(0,-1).map((p,i)=>rectSegmentDistance(e.labelBox!,p,e.points[i+1])))>24)return fail({code:'INVALID_GEOMETRY',rule:'label-association',ids:[e.id],message:'label is detached from its connector'});if(scene.nodes.some(n=>overlap(e.labelBox!,n.box)))return fail({code:'INVALID_GEOMETRY',rule:'label-clearance',ids:[e.id],message:'label overlaps node'});for(const other of scene.edges)for(let i=0;i<other.points.length-1;i++)if(segHitsRect(other.points[i],other.points[i+1],e.labelBox))return fail({code:'INVALID_GEOMETRY',rule:'label-edge',ids:[e.id,other.id],message:'label overlaps edge'});}
 }
 for(let i=0;i<scene.edges.length;i++)for(let j=i+1;j<scene.edges.length;j++){const a=scene.edges[i],b=scene.edges[j];if(a.labelBox&&b.labelBox&&overlap(a.labelBox,b.labelBox))return fail({code:'INVALID_GEOMETRY',rule:'label-label',ids:[a.id,b.id],message:'edge labels overlap'});}
 // Label tethers must identify exactly their owner and reach their label boundary.
 for(const e of scene.edges)if(e.leader){
  if(!e.labelBox||e.leader.length!==2||!e.labelAnchor)return fail({code:'INVALID_GEOMETRY',rule:'label-leader',ids:[e.id],message:'label tether lacks its anchor or bounds'});
  const [a,b]=e.leader;
  const onSegment=(p:Point,c:Point,d:Point)=>c.x===d.x?Math.abs(p.x-c.x)<EPS&&p.y>=Math.min(c.y,d.y)-EPS&&p.y<=Math.max(c.y,d.y)+EPS:Math.abs(p.y-c.y)<EPS&&p.x>=Math.min(c.x,d.x)-EPS&&p.x<=Math.max(c.x,d.x)+EPS;
  if(!finite(a)||!finite(b)||!(a.x===b.x||a.y===b.y)||!boundary(b,e.labelBox)||!e.points.slice(0,-1).some((p,i)=>onSegment(a,p,e.points[i+1])))return fail({code:'INVALID_GEOMETRY',rule:'label-leader',ids:[e.id],message:'label tether is detached from its owner or label'});
  for(const n of scene.nodes)if(segHitsRect(a,b,n.box))return fail({code:'INVALID_GEOMETRY',rule:'label-leader-clearance',ids:[e.id,n.id],message:'label tether crosses a node'});
  for(const other of scene.edges)if(other.id!==e.id){
   if(other.labelBox&&segHitsRect(a,b,other.labelBox))return fail({code:'INVALID_GEOMETRY',rule:'label-leader-clearance',ids:[e.id,other.id],message:'label tether crosses another label'});
   for(let i=0;i<other.points.length-1;i++){
    const c=other.points[i],d=other.points[i+1];
    const crossing=a.x===b.x&&c.y===d.y?a.x>=Math.min(c.x,d.x)-EPS&&a.x<=Math.max(c.x,d.x)+EPS&&c.y>=Math.min(a.y,b.y)-EPS&&c.y<=Math.max(a.y,b.y)+EPS:a.y===b.y&&c.x===d.x?c.x>=Math.min(a.x,b.x)-EPS&&c.x<=Math.max(a.x,b.x)+EPS&&a.y>=Math.min(c.y,d.y)-EPS&&a.y<=Math.max(c.y,d.y)+EPS:false;
    if(crossing)return fail({code:'INVALID_GEOMETRY',rule:'label-leader-clearance',ids:[e.id,other.id],message:'label tether crosses another connector'});
   }
  }
 }

 // independent segment checks: parallel overlap is forbidden; transverse crossings are counted.
 const all=scene.edges.flatMap(e=>e.points.slice(0,-1).map((p,i)=>({id:e.id,a:p,b:e.points[i+1]})));
 for(let i=0;i<all.length;i++)for(let j=i+1;j<all.length;j++){const x=all[i],y=all[j];if(x.id===y.id)continue;const xv=x.a.x===x.b.x,yv=y.a.x===y.b.x;if(xv===yv){if((xv&&Math.abs(x.a.x-y.a.x)<CLEAR+STROKE)||( !xv&&Math.abs(x.a.y-y.a.y)<CLEAR+STROKE)){const lo=Math.max(xv?Math.min(x.a.y,x.b.y):Math.min(x.a.x,x.b.x),xv?Math.min(y.a.y,y.b.y):Math.min(y.a.x,y.b.x));const hi=Math.min(xv?Math.max(x.a.y,x.b.y):Math.max(x.a.x,x.b.x),xv?Math.max(y.a.y,y.b.y):Math.max(y.a.x,y.b.x));if(hi>lo+EPS)return fail({code:'INVALID_GEOMETRY',rule:'shared-segment',ids:[x.id,y.id],message:'edges overlap or are too close'});}}else {const v=xv?x:y,h=xv?y:x; if(v.a.x>Math.min(h.a.x,h.b.x)+EPS&&v.a.x<Math.max(h.a.x,h.b.x)-EPS&&h.a.y>Math.min(v.a.y,v.b.y)+EPS&&h.a.y<Math.max(v.a.y,v.b.y)-EPS)crossings++;}}
 for(const c of scene.continuations??[]){const n=scene.nodes.find(x=>x.id===c.throughNode),incoming=scene.edges.find(x=>x.id===c.incomingEdge),outgoing=scene.edges.find(x=>x.id===c.outgoingEdge),ip=scene.ports.find(x=>x.id===`${c.incomingEdge}:target`),op=scene.ports.find(x=>x.id===`${c.outgoingEdge}:source`);if(!n||!incoming||!outgoing||incoming.target!==c.throughNode||outgoing.source!==c.throughNode||!ip||!op||c.points.length<2)return fail({code:'INVALID_GEOMETRY',rule:'continuation',ids:[c.incomingEdge,c.outgoingEdge],message:'invalid continuation declaration'});if(Math.abs(c.entry.x-ip.point.x)>EPS||Math.abs(c.entry.y-ip.point.y)>EPS||Math.abs(c.exit.x-op.point.x)>EPS||Math.abs(c.exit.y-op.point.y)>EPS||Math.abs(c.points[0].x-c.entry.x)>EPS||Math.abs(c.points[0].y-c.entry.y)>EPS||Math.abs(c.points.at(-1)!.x-c.exit.x)>EPS||Math.abs(c.points.at(-1)!.y-c.exit.y)>EPS)return fail({code:'INVALID_GEOMETRY',rule:'continuation-ports',ids:[c.incomingEdge,c.outgoingEdge],message:'continuation does not meet its ports'});if(incoming.color!==outgoing.color||c.color!==incoming.color)return fail({code:'INVALID_GEOMETRY',rule:'continuation-color',ids:[c.incomingEdge,c.outgoingEdge],message:'continuation flow has inconsistent color'});for(let i=1;i<c.points.length;i++){const a=c.points[i-1],b=c.points[i];if(!(a.x===b.x||a.y===b.y)||!boundary(a,n.box)&&!inside(a,n.box)||!boundary(b,n.box)&&!inside(b,n.box)||c.textBounds.some(r=>segHitsRect(a,b,{x:r.x-c.clearance,y:r.y-c.clearance,width:r.width+2*c.clearance,height:r.height+2*c.clearance})))return fail({code:'INVALID_GEOMETRY',rule:'continuation-clearance',ids:[c.incomingEdge,c.outgoingEdge],message:'continuation is not text-safe inside its node'});}}
 const continuationSegments=(scene.continuations??[]).flatMap(c=>c.points.slice(0,-1).map((a,i)=>({id:c.incomingEdge,outgoing:c.outgoingEdge,node:c.throughNode,a,b:c.points[i+1]})));for(let i=0;i<continuationSegments.length;i++)for(let j=i+1;j<continuationSegments.length;j++){const a=continuationSegments[i],b=continuationSegments[j];if(a.id===b.id||a.outgoing===b.outgoing&&a.node===b.node)continue;if(a.a.x===a.b.x&&b.a.x===b.b.x&&Math.abs(a.a.x-b.a.x)<CLEAR||a.a.y===a.b.y&&b.a.y===b.b.y&&Math.abs(a.a.y-b.a.y)<CLEAR){const vertical=a.a.x===a.b.x,lo=Math.max(vertical?Math.min(a.a.y,a.b.y):Math.min(a.a.x,a.b.x),vertical?Math.min(b.a.y,b.b.y):Math.min(b.a.x,b.b.x)),hi=Math.min(vertical?Math.max(a.a.y,a.b.y):Math.max(a.a.x,a.b.x),vertical?Math.max(b.a.y,b.b.y):Math.max(b.a.x,b.b.x));if(hi>lo+EPS)return fail({code:'INVALID_GEOMETRY',rule:'continuation-overlap',ids:[a.id,b.id],message:'continuation tracks overlap'});}}
 return {ok:true,value:scene,report:{ok:true,diagnostics:[],crossings}};
}
